apiVersion: apps/v1
kind: Deployment
metadata:
  name: financemanagement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financemanagement
  template:
    metadata:
      labels:
        app: financemanagement
    spec:
      containers:
        - name: financemanagement
          image: juancastdh/financemanagement:appv2